version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - ./src/:/opt/spark/app/src
      - ./checkpoint:/opt/spark/app/checkpoint

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077    
    depends_on:
      - spark-master

  localstack:
    container_name: simulator-aws
    image: localstack/localstack
    command: /bin/sh /tmp/itau-shop/create-bucket.sh
    ports:
      - "4566:4566"            # LocalStack Gateways
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./input/:/tmp/itau-shop/input/
      - ./output/:/tmp/itau-shop/output/
      - ./create-bucket.sh:/tmp/itau-shop/create-bucket.sh
